export const CHANGE_INPUT_FIELD = "CHANGE_INPUT_FIELD";

export const REQUEST_IMAGE_PENDING = 'REQUEST_IMAGE_PENDING';
export const REQUEST_IMAGE_SUCCESS = 'REQUEST_IMAGE_SUCCESS';
export const REQUEST_IMAGE_FAILED = 'REQUEST_IMAGE_FAILED';
